# Generated by Django 5.1.7 on 2025-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
