# Generated by Django 5.1.7 on 2025-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
