# Generated by Django 5.1.7 on 2025-06-07 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.dog'),
        ),
    ]
