# Generated by Django 5.1.7 on 2025-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_favorite_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dog_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
