# Generated by Django 5.1.7 on 2025-06-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_dog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dog_name',
        ),
    ]
