# Generated by Django 5.1.7 on 2025-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_post_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dog_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
