# Generated by Django 5.1.7 on 2025-06-16 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.dog'),
        ),
    ]
