# Generated by Django 5.1.7 on 2025-06-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_birthday_post_breed_post_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='biography',
        ),
    ]
